#!/bin/sh

set -e # exit if an error occured

# make filesystem
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

# base install
mount /dev/sda3 /mnt
pacstrap /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

# chroot
arch-chroot /mnt
ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
hwclock --systohc
echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.hen
locale-gen
# hostname
echo -n "Enter the hostname of this computer: "
read hostname
echo "$hostname" > /etc/hostname
# hosts
echo "\n# Generated by Fanfanlatulipe Fast Installer\n127.0.0.1 localhost\n::1 localhost\n127.0.1.1 $hostname.localdomain $hostname" >> /etc/hosts

echo "Root password (be sure to remember it):"
passwd

echo -n "New sudo user name: "
read username
useradd -m $username
echo "$username new password:"
passwd $username
usermod -aG wheel,audio,video $username

# update pacman
pacman -Sy

# sudo
pacman -S sudo
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

# GRUB & stuff
pacman -S grub
echo "Does this archlinux installed on a EUFI (y/N)?"
read eufi
if [ "$eufi" = y | "$eufi" = yes]; then
    pacman -S efibootmgr dosfstools os prober mtools
    mkdir /boot/EFI
    mount /dev/sda1 /boot/EFI
    grub-install --target=x86_64-efi --bootlloader-id=grub_eufi --recheck
else
    pacman -S dosfstools os prober mtools
    grub-install --target=i386-pc /dev/sda --recheck
fi
grub-mkconfig -o /boot/grub/grub.cfg

# Network
echo "Installing netctl by default. Do you prefer NetworkManager (y/N)?"
read network
if [ "$network" = y | "$network" = yes ]; then
    pacman -S netctl wifi-menu
else
    pacman -S networkmanager
    echo "Enable NetworkManager daemon (y/N)?"
    read daemonNetworkManager
    if [ "$daemonNetworkManager" = y | "$daemonNetworkManager" = yes ]; then
        systemctl enable networkmanager
    fi
fi

install_package () {
    echo "Do you want to install $1 (y/N)?"
    read answer
    if [ "$answer" = y | "$answer" = yes ]; then
        pacman -S $1
        return $?
    fi
    return 1
}

install_package "vim"
install_package "base-devel"

