#!/bin/sh

set -e # exit if an error occured

# make filesystem
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

# base install
mount /dev/sda3 /mnt
pacstrap /mnt base linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

# chroot
archroot () {
    ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
    hwclock --systohc
    echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.hen
    locale-gen
    # hostname
    echo -n "Enter the hostname of this computer: "
    read hostname
    echo "$hostname" > /etc/hostname
    # hosts
    echo "\n# Generated by Fanfanlatulipe Fast Installer\n127.0.0.1 localhost\n::1 localhost\n127.0.1.1 $hostname.localdomain $hostname" >> /etc/hosts

    echo "Root password (be sure to remember it):"
    passwd

    echo -n "New sudo user name: "
    read username
    useradd -m $username
    echo "$username new password:"
    passwd $username
    usermod -aG wheel,audio,video $username

    # update pacman
    pacman -Sy --noconfirm

    # sudo
    pacman -S sudo --noconfirm
    echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

    # GRUB & stuff
    pacman -S grub --noconfirm
    echo "Does this archlinux installed on a EUFI (y/N)?"
    read eufi
    if [[ "$eufi" == [yY] || "$eufi" == [yY][eE][sS] ]]; then
        pacman -S efibootmgr dosfstools os prober mtools --noconfirm
        mkdir /boot/EFI
        mount /dev/sda1 /boot/EFI
        grub-install --target=x86_64-efi --bootlloader-id=grub_eufi --recheck
    else
        pacman -S dosfstools os prober mtools --noconfirm
        grub-install --target=i386-pc /dev/sda --recheck
    fi
    grub-mkconfig -o /boot/grub/grub.cfg

    # Network
    echo "Installing netctl by default. Do you prefer NetworkManager (y/N)?"
    read network
    if [[ "$network" == [yY] || "$network" == [yY][eE][sS] ]]; then
        pacman -S netctl wifi-menu --noconfirm
    else
        pacman -S networkmanager --noconfirm
        echo "Enable NetworkManager daemon (y/N)?"
        read daemonNetworkManager
        if [ "$daemonNetworkManager" = y | "$daemonNetworkManager" = yes ]; then
            systemctl enable networkmanager
        fi
    fi

    install_package () {
        echo "Do you want to install $1 (y/N)?"
        read answer
        if [[ "$answer" == [yY] || "$answer" == [yY][eE][sS] ]]; then
            pacman -S $1 --noconfirm
            return $?
        fi
        return 1
    }

    install_package "vim"
    install_package "base-devel"
}

export -f archroot
arch-root /mnt /bin/sh -c "archroot"

echo "Do you want to unmount /mnt and reboot (y/N)?"
read answer
if [[ "$answer" == [yY] || "$answer" == [yY][eE][sS] ]]; then
    unmount /mnt
    reboot
fi
